appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: caPmfQGhO0RmYx8m8Y97KDbwE3A/b2R8sakobKgaawuP4cta0OGk18HX56bcWE2mvHbQ7OcL560ZXiHhHXTO7mvEB2ccFcbGUCclQcI85T30Fds0CUQ545nHfgWpGEhhnbOOlOc03YMc4Jvy8oAWPg2tuOHRvuDmnnXkYdxJyjXZI4iZwiBNofGC95IugjJNM3zI++jk95EbcGcVdYErt/QwdNDsMnuzYhb2Ma51G9xv6NiQnfahlBAtHJWGqJIuJmpMvfxs+db5D2Jnln/0MDX5qhehWjcmr6jLyg0N15moMbwyBw/rQATHfqlni4sTyQtbuDAVfrJyjaM3mIzx0IFe6PVbeiOW1hBseKr/SrIuZrO6F90IdCfk78sPGjqe7GXpErR33DC6JYSJmpEsGV1Fhkrd8Qd2OOTgbucm5gHWXmiIKxyq2pHJ3IrsVqxaqwOcCQZamAXvt4rGqsaRH2k4HtmVK+hYdgpNyHSTU+mxmbiK7iKny7cJmF/9/nKzAY+fqr+Ju4FPPqtcUwV5IRvbp2gV/hUeiGtXzWRtcT8TYNNgY9xttFm2CmxC1nfbXqrTWjrcikRdbSCOY+aWClIa+2KCby9BUZSvdlWineB/k7/9Uj7cYJqzK5TJC0j4bjkca9IGIwy6safqGFkqk9aN4aQBahFaZ3bRjFJg5P4=}
